server:
  port: 8501
spring:
  application:
    name: bdap-admin
  cloud:
    consul:
      host: bdap-cluster-06
      port: 8500
      discovery:
        enabled: true
        register: true
        instance-id: ${spring.application.name}:${server.port}
        health-check-path: /actuator/health
        health-check-interval: 10s
  boot:
    admin:
      notify:
        mail:
          # 收件人， 多个中间用,分隔
          to: 2450179744@qq.com
          # 发件人
          from: 2450179744@qq.com
      discovery:
        ignored-services: consul
      ui:
        title: 微服务监控
  # 微服务挂了的时候邮件通知
  mail:
    host: smtp.qq.com
    username: 2450179744@qq.com
    password: eerkvnjlojxwdhji

management:
  health:
    redis:
      enabled: false
    consul:
      enabled: true
    binders:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    servlet:
      context-path: /actuator
