server:
  port: 8501
spring:
  application:
    name: bdap-admin
  cloud:
    consul:
      host: bdap-cluster-06
      port: 8500
      discovery:
        enabled: true
        register: true
        instance-id: ${spring.application.name}:${server.port}
        health-check-path: /actuator/health
        health-check-interval: 10s
  boot:
    admin:
      discovery:
        ignored-services: consul
      ui:
        title: 微服务监控

management:
  health:
    redis:
      enabled: false
    consul:
      enabled: true
    binders:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    servlet:
      context-path: /actuator
